# Generated by Django 2.2.6 on 2021-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WestBank', '0002_auto_20210415_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='total_credit',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='total_debit',
            field=models.CharField(max_length=2000),
        ),
    ]
