# Generated by Django 2.2.6 on 2021-04-15 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WestBank', '0003_auto_20210415_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='total_debit',
        ),
        migrations.AddField(
            model_name='transactions',
            name='bankname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='country',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='fullname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='swift',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
